In [21]:
import pandas as pd


df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns=["A", "B", "C"], index=["X","Y","Z"])

df.nunique()

A    3
B    3
C    3
dtype: int64

In [54]:
import numpy as np

coffee = pd.read_csv('C:/Users/makaw002/Music/AI/warmup-data/coffee.csv')

coffee['price'] = 8.99

coffee['New_Price'] = np.where(coffee['Coffee Type'] == 'Espresso',3.99,5.99)

coffee.head()

         Day Coffee Type  Units Sold  price  New_Price
0     Monday    Espresso          25   8.99       3.99
1     Monday       Latte          15   8.99       5.99
2    Tuesday    Espresso          30   8.99       3.99
3    Tuesday       Latte          20   8.99       5.99
4  Wednesday    Espresso          35   8.99       3.99

In [38]:
coffee.sort_values(["Units Sold","Coffee Type"], ascending=[1,0])

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
5   Wednesday       Latte          25
0      Monday    Espresso          25
7    Thursday       Latte          30
2     Tuesday    Espresso          30
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
4   Wednesday    Espresso          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [51]:
bios = pd.read_csv('C:/project/AI/data/bios.csv')

#bios.head()

bios[bios['born_country'].isin(["USA", "FRA"]) & bios['name'].str.startswith("Keith")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN